export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_ADD_SUBJECT_REQUEST = 'USER_ADD_SUBJECT_REQUEST'
export const USER_ADD_SUBJECT_SUCCESS = 'USER_ADD_SUBJECT_SUCCESS'
export const USER_ADD_SUBJECT_FAIL = 'USER_ADD_SUBJECT_FAIL'
export const USER_ADD_SUBJECT_RESET = 'USER_ADD_SUBJECT_RESET'

export const USER_TOP_REQUEST = 'USER_TOP_REQUEST'
export const USER_TOP_SUCCESS = 'USER_TOP_SUCCESS'
export const USER_TOP_FAIL = 'USER_TOP_FAIL'